version: '3'
services:
    app:
        build: ./docker-ruby-hello-world
        networks:
            - deploy-net 
    proxy:
        build: ./nginx
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
        ports:
            - "80:80"
        networks:
            - deploy-net 
networks:
  deploy-net:
