version: '3'
services:

    proxy:
        build: ./nginx
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
        ports:
            - "80:80"
        networks:
            - deploy-net 
networks:
  deploy-net:
