version: 2.1
orbs:

jobs:
  deploy-into-aws:
    parameters:
        ec2-host:
          type: string
        branch-name:
          type: string
    machine:
      enabled: true
    steps:
      - run:
          name: Install git
          command: ssh ec2-user@$ec2_host sudo yum install git -y
      -  run:
          name: Install Git and Pull the git code
          command: ssh ec2-user@$ec2_host git pull origin <<parameters.branch-name>>

      - run:
          name: Stop the running docker containers
          command: ssh ec2-user@<$ec2_host docker-compose down --v
      - run:
          name: Restart the containers
          command: ssh ec2-user@$ec2_host docker-compose up --build -d
      - run:
          name: Run the migrations
          command: ssh ec2-user@$ec2_host "docker exec ic-web rake db:migrate"
workflows:
  build-and-deploy:
    jobs:
      # Deploy staging
      - deploy-into-aws:
          ec2-host: $ec2_host
          branch-name: "main"
          filters:
            branches:
              only:
                - main
      # Deploy PROD
      - deploy-into-aws:
          ec2-host: $RC_EC2_HOST
          branch-name: "produccion"
          filters:
            branches:
              only:
                - produccion
