version: 2.1
orbs:

jobs:
  deploy-into-aws:
    parameters:
        ec2-host:
          type: string
        branch-name:
          type: string
          default: main
    machine:
      enabled: true
    working_directory: ~/main
    steps:
      - add_ssh_keys:
                  fingerprints:
                      - "d5:15:5d:c6:2a:93:e9:02:48:d0:0e:b2:20:20:6c:43"
      - checkout
      - run:
          name: Add Key to Known hosts
          command: ssh-keyscan $ec2_host >> ~/.ssh/known_hosts 
      - run:
          name: Stop the running docker containers
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "cd /home/ec2-user/main; sudo docker-compose down --v" || true
      - run:
          name: Clean Files
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "cd /home/ec2-user; sudo rm -rf *"
      - run:
          name: Clean Images
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "sudo docker rmi $(sudo docker images --quiet)" || true
      - run:
          name: Copy compose and env to remote host
          command: scp -r $PWD ec2-user@$ec2_host:/home/ec2-user         
      - run:
          name: Run Compose + Build
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "cd /home/ec2-user/main; sudo docker-compose  up --build -d"
      - run:
          name: Run the migrations
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "docker exec ic-web rake db:migrate"
workflows:
  build-and-deploy:
    jobs:
      # Deploy staging
      - deploy-into-aws:
          ec2-host: $ec2_host
          branch-name: "main"
          filters:
            branches:
              only:
                - main
      # Deploy PROD
      - deploy-into-aws:
          ec2-host: $RC_EC2_HOST
          branch-name: "produccion"
          filters:
            branches:
              only:
                - produccion
