version: 2.1
orbs:

jobs:
  deploy-into-aws:
    parameters:
        ec2-host:
          type: string
        branch-name:
          type: string
          default: main
    machine:
      enabled: true
    working_directory: ~/main
    steps:
      - add_ssh_keys:
                  fingerprints:
                      - ""
      - checkout
      - run:
          name: Add Key to Known hosts
          command: ssh-keyscan $ec2_host >> ~/.ssh/known_hosts 
      - run:
          name: Stop the running docker containers
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host docker-compose down --v
      - run:
          name: Clean Files
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "cd /home/ec2-user; sudo rm -rf *"
      - run:
          name: Clean Images
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "sudo docker rmi -f $(sudo docker images -a -q)"
      - run:
          name: Copy compose and env to remote host
          command: scp -r $PWD/main/* ec2-user@$ecs_host:/home/ec2-user         
      - run:
          name: Run Compose + Build
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host docker-compose up --build -d
      - run:
          name: Run the migrations
          command: ssh -o StrictHostKeyChecking=no ec2-user@$ec2_host "docker exec ic-web rake db:migrate"
workflows:
  build-and-deploy:
    jobs:
      # Deploy staging
      - deploy-into-aws:
          ec2-host: $ec2_host
          branch-name: "main"
          filters:
            branches:
              only:
                - main
      # Deploy PROD
      - deploy-into-aws:
          ec2-host: $RC_EC2_HOST
          branch-name: "produccion"
          filters:
            branches:
              only:
                - produccion
